# Alembic script.py.mako — template for auto-generated revisions
"""add agent_runner_state table for host-owned persistent state

Revision ID: 6dfd3dd7f0c7
Revises: a1b2c3d4e5f6
Create Date: 2026-05-23 19:49:08.529110
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '6dfd3dd7f0c7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runner_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runner_id', sa.String(length=255), nullable=False),
    sa.Column('binding_identity', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('scope_key', sa.String(length=512), nullable=False),
    sa.Column('state_key', sa.String(length=255), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('bot_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'state_key', name='uq_agent_runner_state_scope_key_state_key')
    )
    with op.batch_alter_table('agent_runner_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runner_state_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runner_state_binding_identity'), ['binding_identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runner_state_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runner_state_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_agent_runner_state_runner_binding', ['runner_id', 'binding_identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runner_state_runner_id'), ['runner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runner_state_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runner_state_scope_key'), ['scope_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runner_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_scope_key'))
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_scope'))
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_runner_id'))
        batch_op.drop_index('ix_agent_runner_state_runner_binding')
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_bot_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_binding_identity'))
        batch_op.drop_index(batch_op.f('ix_agent_runner_state_actor_id'))

    op.drop_table('agent_runner_state')
    # ### end Alembic commands ###
