apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: synthorai-chat-completions
  label:
    en_US: Synthorai
    zh_Hans: Synthorai
  icon: synthorai.svg
spec:
  litellm_provider: openai
  config:
    - name: base_url
      label:
        en_US: Base URL
        zh_Hans: 基础 URL
      type: string
      required: true
      default: https://synthorai.io/v1
    - name: timeout
      label:
        en_US: Timeout
        zh_Hans: 超时时间
      type: integer
      required: true
      default: 120
  alias: "synthorai Synthorai 网关 聚合 中转 路由 openai anthropic claude gpt gemini glm kimi deepseek qwen"
  support_type:
    - llm
  provider_category: maas
execution:
  python:
    path: ./chatcmpl.py
    attr: OpenAIChatCompletions
