admins: []
api:
    port: 5300
command:
    enable: true
    prefix:
    - '!'
    - ！
    privilege: {}
concurrency:
    pipeline: 20
    session: 1
mcp:
    servers: []
proxy:
    http: ''
    https: ''
system:
    recovery_key: ''
    jwt:
        expire: 604800
        secret: ''
kb:
    default_vector_db: chroma
    qdrant:
        url: ''
        host: localhost
        port: '6333'
        api_key: ''
