name: Build Docker Image

on:
  release:
    types: [published]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Build image
    env:
      IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}/langbot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare GITHUB_REF
        run: |
          if [ -z "$GITHUB_REF" ]; then
            export GITHUB_REF=${{ github.ref }}
            echo "$GITHUB_REF"
          fi

      - name: Check version
        id: check_version
        run: |
          echo "$GITHUB_REF"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=$(echo "$GITHUB_REF" | awk -F '/' '{print $3}')
          else
            VERSION="${GITHUB_REF}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Buildx
        run: docker buildx create --name mybuilder --use

      - name: Build for Release
        if: ${{ github.event.release.prerelease == false }}
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t ${IMAGE_REPO}:${{ steps.check_version.outputs.version }} \
            -t ${IMAGE_REPO}:latest \
            . --push

      - name: Build for Pre-release
        if: ${{ github.event.release.prerelease == true }}
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t ${IMAGE_REPO}:${{ steps.check_version.outputs.version }} \
            . --push
